export const expenditureCat = [
    "Advertising and Marketing", 
    "Automobile Expense",
    "Consultant Expense",
    "Credit Card Charges",
    "Depreciation Expense",
    "IT and Internet Expenses",
    "Janitorial Expense",
    "Lodging",
    "Meals and Entertainment",
    "Office Supplies",
    "Postage",
    "Printing and Stationery",
    "Rent Expense ",
    "Repairs and Maintenance",
    "Salaries and Expenses Wages",
    "Telephone Expense",
    "Travel Expense",
    "Fixed Assets",
    "Expenses",
    "SNNIT",
    "Bank Charges",
    "Cleaning and Sanitation",
    "Fuel/Lubrication",
    "Vehicle Maintenance",
    "Accountancy",
    "Learning Materials",
    "Proprietor Drawings",
    "Donation/Gift",
    "Permit/Levies/Rates",
    "Electricity",
    "Water",
    "Text Book",
    "Note books",
    "School Uniform",
    "Exams Printing",
    "Maintenance",
    "Others"
]

export const bankOptions = [
    "Barclays Bank", 
    "Stanbic",
    "Standard Chartered Bank",
    "Trust Bank",
    "UT Bank",
    "United Bank for Africa"
]